/*
 * This source file was generated by the Gradle 'init' task
 */
package sisop_trab_2;

public class App {

    public static void main(String[] args) {

        Config config = new Config(
                10, // bits do endereço virtual (2^10 = 1024 bytes)
                12, // bits da memória física (2^12 = 4096 bytes)
                4, // bits da página (2^4 = 16 bytes por página)
                128, 128, 128 // tamanhos dos segmentos em bytes
        );
        Simulador simulador = new Simulador(config);
        try {

            String nomeArquivo = args[0];
            simulador.executar(nomeArquivo, "saida.txt");
            System.out.println("Simulação concluída. Resultados salvos em 'saida.txt'.");
        } catch (Exception e) {
            System.out.println("Erro: Argumento nao e um arquivo valido. Usando arquivo de exemplo.\n");
          //  simulador.executar("arquivo_entrada.txt", "saida.txt");

        }
    }
}