/*
 * This source file was generated by the Gradle 'init' task
 */
package sisop_trab_2;

public class App {

    public static void main(String[] args) {

        Config config = new Config(
                12, // bits do endereço virtual 
                10, // bits da memória física
                4, // bits da página 
                128, 128, 128 // tamanhos dos segmentos em bytes
        );

        Simulador simulador = new Simulador(config);

        if(args.length == 0) {
            System.out.println("Erro: Nenhum arquivo de entrada fornecido. Usando arquivo de exemplo.\n");
            args = new String[]{"arquivo_entrada.txt"}; // arquivo de exemplo
        }

        try {
            String nomeArquivo = args[0];
            simulador.executar(nomeArquivo, "saida.txt");
            System.out.println("Simulacao concluida. Resultados salvos em 'saida.txt'.");
        } catch (Exception e) {
            throw new RuntimeException("Erro ao executar a simulacao: " + e.getMessage(), e);
        }
    }
}